---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Choose which apps to deploy (components are optional)
components:
  # Note: openshift-gitops-operator is for manual bootstrap only, not app-of-apps
  
  # Centralized InstallPlan Approval (sync-wave 1)
  - ../components/installplan-approver-operator     # Operator + multi-namespace CR
  
  # OpenShift GitOps - managed by ArgoCD (sync-wave 0, 3)
  - ../components/openshift-gitops-custom                    # ArgoCD configuration
  - ../components/openshift-gitops-with-auto-approval        # Operator self-management (uses centralized approval)
  
  # OLM Operators - all use centralized approval (sync-wave 5)
  - ../components/gitlab-runner-operator
  - ../components/cert-manager-operator

# Cluster-specific labels
labels:
  - pairs:
      cluster: dev-cluster
      environment: homelab

# Example: Add cluster-specific patches here
# patches:
#   - target:
#       kind: Application
#       name: gitlab-runner-operator
#     patch: |-
#       - op: replace
#         path: /spec/source/path
#         value: ocp/gitlab-runner-operator/overlays/dev-cluster

