---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-instance-gitops-config
  namespace: openshift-gitops
  labels:
    app-type: config
    argoproj.io/sync-wave: "0"
spec:
  project: default
  
  source:
    repoURL: https://github.com/rajinator/k8s-apps-repo
    targetRevision: v0.1.0
    path: ocp/openshift-gitops-operator/overlays/custom
  
  destination:
    name: in-cluster
    namespace: openshift-gitops
  
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - FailOnSharedResource=true # Fail if multiple argo apps are managing the same resource
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

