---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-cluster
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "15"
  labels:
    app.kubernetes.io/name: rook-ceph-cluster
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: platform
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: default
  source:
    path: platform/configs/rook-ceph/overlays/ocp4-d2
    repoURL: https://github.com/rajinator/ocp-gitops-repo
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false  # Namespace already exists from operator
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
  # Custom health check for CephCluster
  ignoreDifferences:
    - group: ceph.rook.io
      kind: CephCluster
      jsonPointers:
        - /status

