---
# ArgoCD Application for InstallPlan Approver Operator
# Deploys the operator only (CRD + operator deployment)
# Configuration (InstallPlanApprover CRs) is separate: see installplan-approver-config
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: installplan-approver-operator
  namespace: openshift-gitops
  labels:
    app-type: operator
    argoproj.io/sync-wave: "1"
spec:
  project: default
  
  source:
    repoURL: https://github.com/rajinator/private-k8s-apps-repo
    targetRevision: main
    path: ocp/installplan-approver-operator/base
  
  destination:
    name: in-cluster
    namespace: iplan-approver-system
  
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true  # Delete resources in reverse order (namespace last)
      - FailOnSharedResource=true # Fail if multiple argo apps are managing the same resource
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

